export const firmConfig = {
  name: "Clinch Wealth Management",
  shortName: "CLINCH",
  tagline: "TO LISTEN. TO PLAN. TOGETHER.",
  colors: {
    primary: "#2C3B2D",
    background: "#F2EFE9",
    accent: "#B5A07A",
    text: "#1A1A1A",
    sage: "#8A9E8C",
    rose: "#C4A8A0",
    surface: "#FFFFFF",
    border: "#E2DDD6",
  },
  fonts: {
    heading: "Playfair Display",
    body: "Inter",
  },
  loggedInAdvisor: {
    id: "advisor_andrew",
    name: "Andrew O'Donohoe",
    title: "Director",
    photo: "/advisors/andrew-odonohoe.jpg",
    initials: "AO",
  },
  advisors: [
    { id: "advisor_andrew", name: "Andrew O'Donohoe", title: "Director", photo: "/advisors/andrew-odonohoe.jpg", initials: "AO" },
    { id: "advisor_tom", name: "Tom Clinch", title: "Managing Director", photo: "/advisors/tom-clinch.jpg", initials: "TC" },
    { id: "advisor_leona", name: "Leona Nicholson", title: "Senior Financial Planner", photo: "/advisors/leona-nicholson.jpg", initials: "LN" },
    { id: "advisor_graham", name: "Graham Brooks", title: "Portfolio Manager", photo: "/advisors/graham-brooks.jpg", initials: "GB" },
    { id: "advisor_donal", name: "Donal Coughlan", title: "Financial Advisor", photo: "/advisors/donal-coughlan.jpg", initials: "DC" },
    { id: "advisor_siobhan", name: "Michele McGuirk", title: "Investment Analyst", photo: "/advisors/michele-mcguirk.jpg", initials: "MM" },
    { id: "advisor_ciaran", name: "Ciaran Giles", title: "Financial Planner", photo: "/advisors/ciaran-giles.jpg", initials: "CG" },
  ],
  clientCount: 200,
  totalAUM: "€142m",
  reportingFooter: "Prepared by Clinch Wealth Management — Confidential",
  reportingDisclaimer: "This report is for information purposes only and does not constitute investment advice.",
}
