export const firmConfig = {
  name: "Kestrel Capital",
  shortName: "KESTREL",
  tagline: "INDEPENDENT. TRUSTED. INVESTED.",
  colors: {
    primary: "#004750",
    background: "#FAFAFA",
    accent: "#A67959",
    text: "#283745",
    sage: "#7A9099",
    rose: "#C4B8AE",
    surface: "#FFFFFF",
    border: "#E0DEDA",
  },
  fonts: {
    heading: "DM Serif Display",
    body: "Jost",
  },
  loggedInAdvisor: {
    id: "advisor_andrew",
    name: "Andrew O'Donohoe",
    title: "Director",
    photo: "/advisors/andrew-odonohoe.jpg",
    initials: "AO",
  },
  advisors: [
    { id: "advisor_andrew", name: "Andrew O'Donohoe", title: "Director", photo: "/advisors/andrew-odonohoe.jpg", initials: "AO" },
    { id: "advisor_tom", name: "Tom Kestrel", title: "Managing Director", photo: "/advisors/tom-clinch.jpg", initials: "TK" },
    { id: "advisor_leona", name: "Leona Nicholson", title: "Senior Financial Planner", photo: "/advisors/leona-nicholson.jpg", initials: "LN" },
    { id: "advisor_graham", name: "Graham Brooks", title: "Portfolio Manager", photo: "/advisors/graham-brooks.jpg", initials: "GB" },
    { id: "advisor_donal", name: "Donal Coughlan", title: "Financial Advisor", photo: "/advisors/donal-coughlan.jpg", initials: "DC" },
    { id: "advisor_siobhan", name: "Michele McGuirk", title: "Investment Analyst", photo: "/advisors/michele-mcguirk.jpg", initials: "MM" },
    { id: "advisor_ciaran", name: "Ciaran Giles", title: "Financial Planner", photo: "/advisors/ciaran-giles.jpg", initials: "CG" },
  ],
  clientCount: 200,
  totalAUM: "€142m",
  reportingFooter: "Prepared by Kestrel Capital — Confidential",
  reportingDisclaimer: "This report is for information purposes only and does not constitute investment advice.",
}
