export const firmConfig = {
  name: "Clinch Wealth Management",
  shortName: "CLINCH",
  tagline: "TO LISTEN. TO PLAN. TOGETHER.",
  colors: {
    primary: "#2C3B2D",
    background: "#F2EFE9",
    accent: "#B5A07A",
    text: "#1A1A1A",
    sage: "#8A9E8C",
    rose: "#C4A8A0",
    surface: "#FFFFFF",
    border: "#E2DDD6",
  },
  fonts: {
    heading: "Playfair Display",
    body: "Inter",
  },
  loggedInAdvisor: {
    id: "advisor_andrew",
    name: "Andrew Collins",
    title: "Director",
    photo: "/advisors/andrew-collins.jpg",
    initials: "AC",
  },
  advisors: [
    { id: "advisor_andrew", name: "Andrew Collins", title: "Director", photo: "/advisors/andrew-collins.jpg", initials: "AC" },
    { id: "advisor_tom", name: "Tom Clinch", title: "Managing Director", photo: "/advisors/tom-clinch.jpg", initials: "TC" },
    { id: "advisor_leona", name: "Leona Nicholson", title: "Senior Financial Planner", photo: "/advisors/leona-nicholson.jpg", initials: "LN" },
    { id: "advisor_graham", name: "Graham Brooks", title: "Portfolio Manager", photo: "/advisors/graham-brooks.jpg", initials: "GB" },
    { id: "advisor_donal", name: "Donal Coughlan", title: "Financial Advisor", photo: "/advisors/donal-coughlan.jpg", initials: "DC" },
    { id: "advisor_siobhan", name: "Siobhan Murray", title: "Investment Analyst", photo: "/advisors/siobhan-murray.jpg", initials: "SM" },
    { id: "advisor_ciaran", name: "Ciarán Doyle", title: "Financial Planner", photo: "/advisors/ciaran-doyle.jpg", initials: "CD" },
  ],
  clientCount: 200,
  totalAUM: "€142m",
  reportingFooter: "Prepared by Clinch Wealth Management — Confidential",
  reportingDisclaimer: "This report is for information purposes only and does not constitute investment advice.",
}
